{
 "title": "Tinkoff Investing",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Item", "query": { "query": "label_values(tcs_item, name)" } }
  ]
 },
 "panels": [
  {
   "title": "Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcs_current_price{name=\"$Item\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Expected yeld",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcs_expected_yield{name=\"$Item\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Current price(sum)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tcs_item{name=\"$Item\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "item info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Currency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "USD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcs_current_price{ticker=\"USD000UTSTOM\"}",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "EUR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcs_current_price{ticker=\"EUR_RUB__TOM\"}",
     "legendFormat": "EUR"
    }
   ]
  },
  { "title": "Портфели", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Брокерский счет",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcs_item{currency=\"USD\", account=\"Tinkoff\"} * scalar(tcs_current_price{ticker=\"USD000UTSTOM\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "tcs_item{account=\"Tinkoff\", currency=\"RUB\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "ИИС",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcs_item{account=\"TinkoffIis\", currency=\"RUB\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "tcs_item{account=\"TinkoffIis\", currency=\"USD\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Общая цена портцеля в разных валютах",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(tcs_item{currency=\"RUB\"}) + sum(tcs_item{currency=\"USD\"}) * scalar(tcs_current_price{ticker=\"USD000UTSTOM\"})",
     "legendFormat": "RUB"
    },
    {
     "expr": "(sum(tcs_item{currency=\"RUB\"}) / scalar(tcs_current_price{ticker=\"USD000UTSTOM\"})) + sum(tcs_item{currency=\"USD\"})",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Текущий доход в рублях",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "currencyRUB" }
   ],
   "targets": [
    {
     "expr": "sort(tcs_expected_yield{type=\"Stock\", currency=\"RUB\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort(tcs_expected_yield{type=\"Stock\", currency=\"USD\"} * scalar(tcs_current_price{ticker=\"USD000UTSTOM\"}))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Текущий доход в долларах",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "tcs_expected_yield{type=\"Stock\", currency=\"RUB\"} / scalar(tcs_current_price{ticker=\"USD000UTSTOM\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "tcs_expected_yield{type=\"Stock\", currency=\"USD\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Pie charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Весь портфель(в пересчете на рубли)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcs_item{currency=\"RUB\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "tcs_item{currency=\"USD\"} * scalar(tcs_current_price{ticker=\"USD000UTSTOM\"})",
     "legendFormat": "{{ name }}"
    },
    {}
   ]
  },
  {
   "title": "Девирсификация портфеля",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "format": "currencyUSD",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Stock\", currency=\"USD\"} * scalar(tcs_current_price{ticker=\"USD000UTSTOM\"}))",
     "legendFormat": "Акции, USD"
    },
    {
     "expr": "sum(tcs_item{type=\"Stock\", currency=\"RUB\"})",
     "legendFormat": "Акции, RUB"
    },
    {
     "expr": "sum(tcs_item{type=\"Bond\", currency=\"RUB\"})",
     "legendFormat": "Облигации, RUB"
    },
    {
     "expr": "sum(tcs_item{type=\"Bond\", currency=\"USD\"} * scalar(tcs_current_price{ticker=\"USD000UTSTOM\"}))",
     "legendFormat": "Облигации, USD"
    },
    {
     "expr": "tcs_item{type=\"Currency\", name=\"Доллар США\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "tcs_item{type=\"Currency\", name=\"Евро\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Bonds",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcs_item{type=\"Bond\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Stock, USD",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "format": "currencyUSD",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcs_item{type=\"Stock\", currency=\"USD\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Stocks, RUB",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcs_item{type=\"Stock\", currency=\"RUB\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}